import { SyntaxStyle } from "@opentui/core"

export type Colors = typeof colors
export const colors = {
  background: "#0a0a0a",
  backgroundPanel: "#141414",
  backgroundElement: "#1e1e1e",
  borderSubtle: "#3c3c3c",
  border: "#484848",
  borderActive: "#606060",
  primary: "#fab283",
  secondary: "#5c9cf5",
  accent: "#9d7cd8",
  error: "#e06c75",
  warning: "#f5a742",
  success: "#7fd88f",
  info: "#56b6c2",
  text: "#eeeeee",
  textMuted: "#808080",
  markdownText: "#eeeeee",
  markdownHeading: "#eeeeee",
  markdownLink: "#fab283",
  markdownLinkText: "#56b6c2",
  markdownCode: "#7fd88f",
  markdownBlockQuote: "#e5c07b",
  markdownEmph: "#e5c07b",
  markdownStrong: "#f5a742",
  markdownHorizontalRule: "#808080",
  markdownListItem: "#fab283",
  markdownListEnumeration: "#56b6c2",
  markdownImage: "#fab283",
  markdownImageText: "#56b6c2",
  markdownCodeBlock: "#eeeeee",
  syntaxComment: "#808080",
  syntaxKeyword: "#9d7cd8",
  syntaxFunction: "#fab283",
  syntaxVariable: "#eeeeee",
  syntaxString: "#7fd88f",
  syntaxNumber: "#e5c07b",
  syntaxType: "#56b6c2",
  syntaxOperator: "#56b6c2",
  syntaxPunctuation: "#eeeeee",
}

export type MarkdownTheme = typeof markdownTheme
export const markdownTheme = {
  h1: {
    bold: true,
    marginTop: 2,
    marginBottom: 1,
    borderBottom: true,
  },
  h2: {
    bold: true,
    marginTop: 1,
    underline: true,
  },
  paragraph: {
    wrap: true,
    marginBottom: 1,
  },
  codeBlock: {
    border: true,
    syntaxHighlight: true,
    padding: 1,
  },
  blockquote: {
    leftBorder: true,
    dim: true,
  },
}

export function markdownSyntax(c: Colors = colors) {
  return SyntaxStyle.fromTheme([
    { scope: ["default"], style: { foreground: c.markdownText } },
    { scope: ["markup.heading"], style: { foreground: c.markdownHeading, bold: true } },
    { scope: ["markup.heading.1"], style: { foreground: c.markdownHeading, bold: true, underline: true } },
    { scope: ["markup.heading.2"], style: { foreground: c.markdownHeading, bold: true } },
    { scope: ["markup.heading.3"], style: { foreground: c.markdownHeading, bold: true } },
    { scope: ["markup.heading.4"], style: { foreground: c.markdownHeading, bold: true } },
    { scope: ["markup.heading.5"], style: { foreground: c.markdownHeading, bold: true } },
    { scope: ["markup.heading.6"], style: { foreground: c.markdownHeading, bold: true } },
    { scope: ["markup.bold", "markup.strong"], style: { foreground: c.markdownStrong, bold: true } },
    { scope: ["markup.italic"], style: { foreground: c.markdownEmph, italic: true } },
    { scope: ["markup.list"], style: { foreground: c.markdownListItem } },
    { scope: ["markup.list.enumerator"], style: { foreground: c.markdownListEnumeration } },
    { scope: ["markup.quote"], style: { foreground: c.markdownBlockQuote, italic: true } },
    { scope: ["markup.raw", "markup.raw.block"], style: { foreground: c.markdownCode } },
    { scope: ["markup.raw.inline"], style: { foreground: c.markdownCode, background: c.background } },
    { scope: ["markup.link"], style: { foreground: c.markdownLink, underline: true } },
    { scope: ["markup.link.label"], style: { foreground: c.markdownLinkText, underline: true } },
    { scope: ["markup.link.url"], style: { foreground: c.markdownLink, underline: true } },
    { scope: ["label"], style: { foreground: c.markdownLinkText } },
    { scope: ["string.special", "string.special.url"], style: { foreground: c.markdownLink, underline: true } },
    { scope: ["markup.strikethrough"], style: { foreground: c.textMuted } },
    { scope: ["markup.underline"], style: { foreground: c.text, underline: true } },
    { scope: ["markup.list.checked"], style: { foreground: c.success } },
    { scope: ["markup.list.unchecked"], style: { foreground: c.textMuted } },
    { scope: ["markup.rule"], style: { foreground: c.markdownHorizontalRule } },
    { scope: ["conceal"], style: { foreground: c.textMuted } },
    { scope: ["comment"], style: { foreground: c.syntaxComment, italic: true } },
    { scope: ["keyword"], style: { foreground: c.syntaxKeyword } },
    { scope: ["function"], style: { foreground: c.syntaxFunction } },
    { scope: ["string"], style: { foreground: c.syntaxString } },
    { scope: ["number"], style: { foreground: c.syntaxNumber } },
    { scope: ["type"], style: { foreground: c.syntaxType } },
    { scope: ["operator"], style: { foreground: c.syntaxOperator } },
    { scope: ["punctuation"], style: { foreground: c.syntaxPunctuation } },
  ])
}
